### ISSUE TITLE
Dead Link under Section-3(3.2 GENERAL)

### ISSUE THREAD

**Issue by AnuragAnalog** [kostasx/LearnJavascript#6]
When I go to the below link, it says the page is not found.

[https://github.com/kostasx/LearnJavascript#32-general](https://github.com/kostasx/LearnJavascript#32-general)

**Comment by AnuragAnalog** [comment]
@kostasx

**Comment by kostasx** [comment]
Thank you for pointing this out @AnuragAnalog. I've reviewed the `General` section and updated a couple of links.

I've also added you as a contributor. :)

Let me know if you found any other broken links or else I can close this issue.

**Comment by AnuragAnalog** [comment]
Thanks, @kostasx, I will search for any broken links in the readme file.

**Comment by AnuragAnalog** [comment]
Under section 3.1

I found a few headings, which are broken they are:

* Javascript: BEST PRACTICES PART 1, by Christian Heilmann
* JAVASCRIPT FUNDAMENTALS, by Azat Mardan
* 7 JavaScript Basics Many Developers Aren't Using (Properly)
* 45 Useful JavaScript Tips, Tricks and Best Practices

**Comment by kostasx** [comment]
You're the best @AnuragAnalog!

Just updated the links.
